apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-app
spec:
  replicas: 2  # two pods, one per availability zone for redundancy
  selector:
    matchLabels:
      app: wiz-app # tells the deployment to manage any pod that has the wiz-app label 
  template:
    metadata:
      labels:
        app: wiz-app # required to specifiy the label for matchLabels
    spec:
      # ensures the two pod replicas land on different availability zones instead of by chance
      topologySpreadConstraints:
        - maxSkew: 1 # allows max 1 pod difference between zones
          topologyKey: topology.kubernetes.io/zone # scheduler groups nodes by this label
          whenUnsatisfiable: DoNotSchedule 
          labelSelector:
            matchLabels:
              app: wiz-app
      serviceAccountName: wiz-service-account # service account created in rbac.yaml
      containers:
        - name: wiz-app
          image: 795176247566.dkr.ecr.us-east-1.amazonaws.com/wiz-ecr-repo:latest # image uploaded to ECR w/ app code
          ports: # declaration that the container is listening on the pod's port 8080
            - containerPort: 8080
          env: # environment variable, so app can login to mongodb on the EC2 instance  
            - name: MONGODB_URI
              value: "mongodb://admin:wizlab123@mongodb.route53rocks.internal:27017/go-mongodb?authSource=admin"
 #/go-mongodb?authSource=admin" is a query parameter that tells mongo where to look up the user credentials. We created the admin user in the admin database.
 # it will check for the admin user in the admin database since we have authSource=admin
 #/go-mongodb specifies the application to use the go-mongodb database for its data.  
