name: Wiz App CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "app/tasky/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # runs git clone on the vm so files are accessible

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3 # download kubectl

      - name: Login to AWS # login to aws with github secrets
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image # runs docker build so we have an image
        working-directory: app/tasky/
        run: |
          docker build -t wiz-app .

      - name: Scan with Trivy # Trivy scan per exercise
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: wiz-app:latest
          severity: LOW,MEDIUM,HIGH,CRITICAL
          exit-code: 0 # so we dont get stuck detections, says exit successfully regardless. (fail here in production)

      - name: Tag for ECR # tags image with :latest for ecr upload, mutability
        run: |
          docker tag wiz-app:latest 795176247566.dkr.ecr.us-east-1.amazonaws.com/wiz-ecr-repo:latest

      - name: Push to ECR # ecr fully compatible with docker
        run: |
          docker push 795176247566.dkr.ecr.us-east-1.amazonaws.com/wiz-ecr-repo:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name wiz-cluster

      - name: Deploy to EKS
        run: kubectl rollout restart deployment wiz-app # restart one pod at a time

