name: Nuke
on:
  workflow_dispatch: # manual trigger only

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        # || true so pipeline continues even if cluster doesnt exist, if it fails, run "true" so it continues
        run: aws eks update-kubeconfig --region us-east-1 --name wiz-cluster || true

      - name: Delete ingress and clear finalizer
        run: |
          # delete the ingress, tells the load balancer controller to remove the ALB
          kubectl delete ingress wiz-ingress --ignore-not-found || true
          # immediately patch the finalizer to empty so deletion never hangs
          # finalizer is a lock kubernetes puts on the ingress to prevent deletion until the ALB is cleaned up
          # if the controller gets confused and never removes it we force clear it here. It sets finalizers in metadata for ingress to 0
          kubectl patch ingress wiz-ingress -p '{"metadata":{"finalizers":[]}}' --type=merge || true

      - name: Wait for ALB to be deleted
        # 60 second buffer to give the controller time to remove the ALB before terraform destroy
        run: sleep 60

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade

      - name: Terraform Destroy
        working-directory: terraform
        # force_destroy = true on the S3 bucket in s3.tf handles emptying the bucket automatically
        # so we no longer need to manually empty it before destroy
        run: terraform destroy -auto-approve

# Purpose: togglable clean slate button. After destroy push to terraform/ or trigger infra pipeline to rebuild.
