name: Wiz Infra CI/CD Pipeline
on: # defines what triggers this workflow
  workflow_dispatch: # allows manual trigger from github ui
  push:
    branches: ["main"] # triggers on push to main branch
    paths:
      - "terraform/**" # only triggers when terraform files change
      - "k8s/**" # only triggers when kubernetes manifests change
      - ".github/workflows/**" # triggers on workflow changes
jobs:
  terraform: # job name
    name: Terraform Plan and Apply # display name in github ui
    runs-on: ubuntu-latest # github spins up a fresh ubuntu VM for every run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # runs git clone on the vm so our files are accessible
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2 # downloads and installs terraform onto the vm
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3 # installs kubectl onto the runner
      - name: Cache Terraform providers
        uses: actions/cache@v3 # saves and restores a directory between runs to avoid re-downloading
        with:
          path: terraform/.terraform # the directory containing downloaded providers to cache
          key: terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }} # unique cache key - changes when lock file changes forcing a fresh download
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2 # sets AWS credentials as environment variables on the vm
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run Checkov IaC Security Scan
        uses: bridgecrewio/checkov-action@v12 # scans terraform files for misconfigurations before deploying
        with:
          directory: terraform/
          soft_fail: true # pipeline continues even if checkov finds issues, needed for intentional misconfigs or we get stuck
      - name: Create s3 bucket if it does not exist
         run: |
           # s3api is low level bucket commands
           # head-bucket is an api-call that checks if the bucket exists and if we have permissions to access it
           # specifies the bucket, then 2>/dev/null to throw any errors away silently
           #  
           aws s3api head-bucket --bucket wiz-mongo-backups-tyler 2>/dev/null || \
           aws s3 mb s3://wiz-mongo-backups-tyler --region us-east-1
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade # downloads providers and modules defined in main.tf
      - name: Terraform Validate and Format
        working-directory: terraform
        run: |
          terraform fmt -recursive # reformats .tf files to hashicorp standard style
          terraform validate # checks for syntax errors
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan # dry run - shows what will change without making changes
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve # creates or updates AWS infrastructure
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name wiz-cluster # configures kubectl to talk to our EKS cluster
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/ # applies all yaml files in the k8s folder
